name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["10", "12"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.0
        with:
          local-dir: build
          ftp-server: ftp://ftp.germankuber.com.ar
          ftp-username: Admin@jornadadearquitectura.net
          ftp-password: ${{ secrets.FTP_PASSWORD }}
